let data = [{
        namefood = 'Nấm đùi gà áp chảo kiểu Âu ',
        tye: 'Món Âu',
        img: 'Mind-X\Kitchies\img\1.1.jpg',
        content: `<p>Xem bài trước của mình ở đây: <a href="https://mykitchies.com/2018/06/17/nam-dui-ga-ap-chao-kieu-nhat/">Nấm đùi gà áp chảo kiểu Nhật</a></p>
        <p>Với cảm nhận riêng của mình thì mình vẫn thích kiểu Nhật hơn, chắc vì mình là người châu Á, mặc dù cả 2 kiểu kiểu nào cũng có sự thơm ngon đặc trưng </p>
        <p>Dưới đây là một trong những công thức đơn giản và phổ biến để chế biến nấm áp chảo (có thể nướng) theo phong cách Âu, bổ sung vào từ điển nội trợ của chúng ta.</p>
        <p><strong>NGUYÊN LIỆU: </strong></p>
        <ul>
        <li>2 cây nấm đùi gà</li>
        <li>1 tép tỏi</li>
        <li>1 chút lá mùi tây (parsley, Petersilie)</li>
        <li>1 cọng nhỏ lá hương thảo (Rosemary, Rosmarin)</li>
        <li>1 cọng nhỏ cỏ xạ hương (Thyme, Thymian) &#8211; tùy chọn</li>
        <li>dầu oliu</li>
        <li>chút muối, hạt tiêu</li>
        </ul>
        <p>Nếu không có lá tươi các bạn có thể mua lọ gia vị lá khô có sẵn ở siêu thị, nhanh tiện gọn Mình dùng lọ gia vị khô</p>
        <p><strong>CÁCH LÀM: </strong></p>
        <ol>
        <li>Nấm đùi gà rửa sạch dưới vòi nước, sau đó lau khô, chẻ làm 2-3 theo chiều dọc. Các loại rau thơm băm nhỏ ra, nếu mua gia vị khô thì không cần. Riêng lá hương thảo mùi khá nồng, các bạn tùy chỉnh theo sở thích nhé, như mình thì chỉ cần 1 xíu rắc lên như rắc muối là đủ thơm rồi.</li>
        <li>Tỏi dập dập, băm nhuyễn ra. Hòa tỏi, dầu oliu, muối, tiêu và rau thơm với nhau. Sau đó phết lên mỗi mặt nấm. Đợi khoảng 5-10 phút cho ngấm</li>
        <li>Cho vào chảo hoặc bếp nướng, nướng ở lửa vừa cho đến khi nấm vàng đều 2 mặt. Để tăng thêm mùi thơm cho nấm có thể rán cùng với chút hành tây thái mỏng  <img src="Mind-X\Kitchies\img\1.2.jpg" alt=""></li>
        <li>Ăn kèm thịt nướng, bò bít tết, cốt lết hay cá nướng đều ngon Có thể áp chảo chút cà chua ở lửa to, sau đó ăn kèm các loại rau khác như một món salad.</li>
        </ol>
        <p> <img src="Mind-X\Kitchies\img\1.1.jpg" alt=""></p>
        <p>Chúc các bạn một ngày vui vẻ và đừng quên theo dõi blog của mình qua Email hoặc trang Facebook Mykitchies &#8211; Bếp Á Âu nhé. Yêu các bạn nhiều :X</p>`,
    },
    {
        namefood = ' Bánh Tiramisù chuẩn Ý – Tiramisu recipe',
        tye: 'Món Âu',
        img: 'Mind-X\Kitchies\img\2.1.jpg',
        content: `<p>Sau một vài tuần vắng bóng do bận học hành đi làm lẫn ba chuyện linh tinh mệt người thì mình cũng đã sắp xếp để quay lại với blog thân yêu. Mình chủ yếu hay nấu đồ mặn hơn vì nó thiết thực (chống đói) và phù hợp với hoàn cảnh (bếp núc). Ngó đi ngó lại thì thấy bánh Tiramisu Ý làm nhanh gọn, đơn giản và dễ ăn nên mình quyết định làm lại để còn nhanh chia sẻ với mọi người (thực ra trước đó mình có làm nhưng mà chưa ghi lại bài bản vì hồi đó chưa có viết lách gì hết). Các bạn yên tâm đi mình đã test thử bao nhiêu chuột bạch rồi và ai cũng khen ngon hết nhé, món này làm không hề khó nhưng quan trọng làm phải có tâm nha 😀</p>
        <p>Một vài điều về bánh Tiramisù nổi tiếng của nước Ý:</p>
        <ol>
        <li>Tiramisù Ý như mình tìm hiểu thì có xuất xứ từ vùng Treviso của Ý (chưa đến bao giờ), được làm từ 6 nguyên liệu chính cơ bản là cà phê Espresso, đường, lòng đỏ trứng gà, phô mai mascarpone, bánh Savoiardy (hay còn gọi là bánh lady finger, bánh sampa) và bột cacao không đường. Về sau xuất hiện phiên bản Tiramisu hiện đại gồm rượu hoặc lòng trắng trứng hoặc cả 2. Lòng trắng trứng giúp cho món Tiramisù trở nên lỏng và mềm hơn chút, trong khi nếu chỉ có lòng đỏ và phô mai mascarpone thì nó đặc và chắc hơn hẳn, giống như mình đang ăn bơ mềm ấy.</li>
        <li>Tiramisù Ý được làm bằng trứng sống, sau này vì sợ khuẩn Salmonella có trong trứng nên nhiều người mới thay bằng whipping cream (kem sữa béo, kem bông tuyết), ở Đức tạm thay bằng Schlagsahne nhiều fett (33%-36%). Với Tiramisù làm bằng whipping cream thì ăn sẽ đặc và kem hơn bánh làm với lòng trắng trứng ăn sẽ bông hơn. Riêng lòng đỏ thì đánh cách thủy nhưng không được phép chín quá. Trong bài mình sẽ sử dụng công thức làm với trứng sống. Trứng sống cần chọn loại tươi mới, có nguồn gốc rõ ràng, có thể đã được khử trùng diệt khuẩn nếu có, và <b>để ở nhiệt độ phòng. </b>Trứng gần hết hạn thì khuyến cáo không dùng.</li>
        <li>Cà phê chuyên dùng cho Tiramisù là cà phê Espresso, siêu đắng siêu đặc, và thường được nấu trong ấm Moka (xem hình dưới). Tuy nhiên không phải ai cũng có điều kiện để nấu được cốc cà phê Espresso hoàn hảo nên các bạn có thể chọn 2 cách: chạy ra cửa hàng bánh ngọt cà phê mua Espresso mang về hoặc mua cà phê hòa tan tự về nhà nấu. Với cà phê hòa tan nên chọn loại thật đậm đặc nhé, càng đắng thì bánh càng ngon. Ngọt đi đôi với đắng mới chuẩn hihi. Trong bài mình sử dụng cà phê hòa tan siêu đậm đặc mình mua sẵn ở siêu thị
        <img src="Mind-X\Kitchies\img\2.2.jpg" alt="">
        </li>
        <li>Với Tiramisù dùng rượu: Chọn rượu Masala hoặc Amaretto là hợp nhất. Ngoài ra có thể chọn Kahlua hay loại rượu Rum nào đó mà bạn thấy phù hợp. Việc cho rượu hay không là tùy chọn, nếu gia đình có trẻ nhỏ ăn hoặc không thích ăn đồ ăn có cồn thì bỏ qua, làm bản truyền thống cũng được. Riêng mình thì mình dùng tinh dầu rượu Rum cho dậy mùi thơm nhưng không có cồn (mua cả chai mình cũng hơi xót mà cũng thấy không cần thiết lắm hihi)</li>
        </ol>
        <p>Trong hình gồm: Cà phê đậm đặc hòa tan (mức 8/10), vị rất đắng (tuy không thơm bằng Espresso nhưng tạm chấp nhận được) &#8211; Tinh dầu rượu Rum hãng Dr.Oetker mình mua ở siêu thị Rewe, socola bào vụn (loại chuyên để rắc bánh hoặc làm bánh &#8211; tùy chọn) và bột cacao không đường. Tất cả các bạn có thể mua được ở siêu thị Rewe</p>
        <p><img src="Mind-X\Kitchies\img\2.3.jpg" alt="">   /></p>
        <p>Dưới đây mình sẽ hướng dẫn các bạn làm công thức Tiramisù Ý theo 2 cách: cách truyền thống và cách hiện đại, tức là có lòng trắng trứng và không có lòng trắng trứng. Ngoài ra mình sẽ chú thích thêm nguyên liệu cũng như phương pháp thay thế dành cho những bạn ngại ăn trứng sống.</p>
        <p><b>NGUYÊN LIỆU:</b></p>
        <ul>
        <li>6 lòng đỏ trứng (mình dùng cỡ M) ở nhiệt độ phòng (trứng phải tươi mới)</li>
        <li>4 lòng trắng trứng (tùy chọn), hoặc thay bằng 300-350ml whipping cream (schlagsahne)</li>
        <li>500gr mascarpone (tương đương 2 hộp- mình mua mascapone hãng Galbani của Ý, bán ở Rewe)</li>
        <li>36-48 bánh lady finger (Savoiardy)</li>
        <li>120gr đường, có thể dùng 100gr nếu sợ ngọt</li>
        <li>350ml cà phê Espresso(hoặc cà phê hòa tan đắng tương tự, pha đậm đặc hơn chỉ dẫn trên bao bì)</li>
        <li>2 thìa ăn rượu Masala (tùy chọn), mình dùng 3 tuýp tinh dầu rượu Rum cho thơm</li>
        <li>bột cacao không đường</li>
        <li>socola đã cạo vụn (dùng rắc bánh &#8211; tùy chọn)</li>
        <li>1 cái rây nhỏ để rắc bột cacao</li>
        </ul>
        <img src="Mind-X\Kitchies\img\2.4.jpg" alt="">
        <img src="Mind-X\Kitchies\img\2.5.jpg" alt="">
        <p><b>CÁCH LÀM:</b></p>
        <ol>
        <li>Cà phê đun nóng sau đó để nguội rồi pha rượu vào. Chuẩn bị những nguyên liệu còn lại đầy đủ</li>
        <li>Cho lòng đỏ vào tô cùng một nửa số đường, dùng phới đánh tầm 8-10 phút đến khi trứng trở nên vàng nhạt và nở gấp đôi lượng ban đầu, khi nhấc phới lên thì hỗn hợp hơi keo keo tạo thành sợi.<br />
        Với bạn nào sợ trứng sống thì bắc tô lên nồi, trong nồi có chút nước rồi tiến hành đánh cách thủy trên bếp. Lưu ý không nên để nồi hơi nóng quá khiến trứng bị chín quá. Sau đó bắc ra để nguội<img data-attachment-id="2014" data-permalink="https://mykitchies.com/20180504_2255561250562914/" data-orig-file="https://mykitchies.files.wordpress.com/2018/05/20180504_2255561250562914.jpg" data-orig-size="2160,2160" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="20180504_2255561250562914.jpg" data-image-description="" data-medium-file="https://mykitchies.files.wordpress.com/2018/05/20180504_2255561250562914.jpg?w=300" data-large-file="https://mykitchies.files.wordpress.com/2018/05/20180504_2255561250562914.jpg?w=736" class="alignnone size-full wp-image-2014" src="https://mykitchies.files.wordpress.com/2018/05/20180504_2255561250562914.jpg?w=736" alt="20180504_2255561250562914.jpg" srcset="https://mykitchies.files.wordpress.com/2018/05/20180504_2255561250562914.jpg?w=736 736w, https://mykitchies.files.wordpress.com/2018/05/20180504_2255561250562914.jpg?w=1472 1472w, https://mykitchies.files.wordpress.com/2018/05/20180504_2255561250562914.jpg?w=150 150w, https://mykitchies.files.wordpress.com/2018/05/20180504_2255561250562914.jpg?w=300 300w, https://mykitchies.files.wordpress.com/2018/05/20180504_2255561250562914.jpg?w=768 768w, https://mykitchies.files.wordpress.com/2018/05/20180504_2255561250562914.jpg?w=1024 1024w" sizes="(max-width: 736px) 100vw, 736px"   /></li>
        <li>Cho phô mai mascarpone vào hỗn hợp lòng đỏ, đánh đều để được hỗn hợp nhuyễn gọi là hỗn hợp kem mascarpone</li>
        <li>Cho lòng trắng vào tô riêng cùng với nửa số đường còn lại. Dùng máy đánh trứng đánh hỗn hợp sao cho đạt được chóp nhọn (soft peak). Lưu ý nên bắt đầu đánh từ số nhỏ trước rồi mới từ từ nâng lên số mạnh sau cùng, đề phòng trứng không lên bông được (mình đã bị 1 lần và lòng trắng đánh hoài vẫn lỏng chứ không thể bông nổi). Ngoài ra que đánh phải sạch sẽ và lòng trắng không dính lòng đỏ hay tạp chất khác<br />
        Với bạn nào sợ trứng sống thì làm tương tự với whipping cream nhé.</li>
        <li>Chia hỗn hợp lòng trắng đã đánh bông thành khoảng 3-4 phần nhỏ, dùng thìa spatula múc từng phần cho vào hỗn hợp kem mascarpone, dùng kỹ thuật fold để trộn đều, tức là hất thìa từ dưới dáy lên và trộn theo 1 chiều. Làm lần lượt với toàn bộ lòng trắng đã đánh bông sao cho hỗn hợp cuối ta thu được trông mịn và không bị lợn cợn.<img data-attachment-id="2015" data-permalink="https://mykitchies.com/2018/05/08/banh-tiramisu-chuan-y/photo-1/" data-orig-file="https://mykitchies.files.wordpress.com/2018/05/photo-1.jpg" data-orig-size="640,640" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="photo (1)" data-image-description="" data-medium-file="https://mykitchies.files.wordpress.com/2018/05/photo-1.jpg?w=300" data-large-file="https://mykitchies.files.wordpress.com/2018/05/photo-1.jpg?w=640" class="alignnone size-full wp-image-2015" src="https://mykitchies.files.wordpress.com/2018/05/photo-1.jpg?w=736" alt="photo (1).jpg" srcset="https://mykitchies.files.wordpress.com/2018/05/photo-1.jpg 640w, https://mykitchies.files.wordpress.com/2018/05/photo-1.jpg?w=150 150w, https://mykitchies.files.wordpress.com/2018/05/photo-1.jpg?w=300 300w" sizes="(max-width: 640px) 100vw, 640px"   /></li>
        <li>Nhúng bánh vào hỗn hợp cà phê khoảng 2 giây, không nên nhúng quá lâu khiến bánh bị nát và úng nước quá, thành phẩm bị ướt sẽ không còn ngon nữa. Xếp bánh vào khay, có thể bẻ bánh thành nhiều phần để chèn vào khoảng trống của khay. Sau đó múc hỗn hợp kem phủ lên, dùng thìa dàn đều. Sau đó lặp lại 1 lớp bánh và 1 lớp kem nữa.</li>
        <li>Để tủ lạnh ít nhất là 6 tiếng, lý tưởng nhất là để qua đêm. Lúc đó bánh đã đông lại và ngấm hoàn toàn. Bánh Tiramisu có thể để được trong tủ lạnh khoảng 1 tuần và để đông ở nhiệt độ 0 độ F khoảng 1 năm 🙂</li>
        <li>Rắc bột cacao lên bánh, sử dụng rây để bột được tán đều và mịn hơn. Rắc thêm vụn socola bào nếu thích. Với ý kiến cá nhân mình thì ăn miếng nào rắc cacao miếng đấy. Nếu rắc cả khay mà chưa ăn hết thì 1 lúc sau cacao sẽ bị ướt và nứt mặt trên bánh.
        <p><figure data-shortcode="caption" id="attachment_2016" aria-describedby="caption-attachment-2016" style="width: 2880px" class="wp-caption alignnone"><img data-attachment-id="2016" data-permalink="https://mykitchies.com/2018-05-05-12-13-202111556063/" data-orig-file="https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-202111556063.jpg" data-orig-size="2880,2160" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="2018-05-05-12-13-202111556063.jpg" data-image-description="" data-medium-file="https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-202111556063.jpg?w=300" data-large-file="https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-202111556063.jpg?w=736" class="alignnone size-full wp-image-2016" src="https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-202111556063.jpg?w=736" alt="2018-05-05-12-13-202111556063.jpg" srcset="https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-202111556063.jpg?w=736 736w, https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-202111556063.jpg?w=1472 1472w, https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-202111556063.jpg?w=150 150w, https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-202111556063.jpg?w=300 300w, https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-202111556063.jpg?w=768 768w, https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-202111556063.jpg?w=1024 1024w" sizes="(max-width: 736px) 100vw, 736px"   /><figcaption id="caption-attachment-2016" class="wp-caption-text">:)) nham nhở tí nhưng mà ngon lắm nhé</figcaption></figure></li>
        </ol>
        <p><b>Một vài lưu ý:</b></p>
        <ol>
        <li>Nếu làm Tiramisù có lòng trắng trứng, bánh ăn sẽ bông xốp hơn. Nếu chỉ làm với mascarpone thì bánh ăn sẽ đặc hơn, có độ chắc hơn (giống như ăn bơ mềm ấy). Với bánh dùng whipping cream ăn sẽ kem hơn, ngậy hơn và đặc hơn so với bánh làm với lòng trắng trứng</li>
        <li>Bước 3 và bước 4 nên cố gắng thực hiện nhanh gọn, tránh lề mề để lâu khiến cho mascarpone mềm đi và hỗn hợp trở nên lỏng, bị chảy nước sẽ khó phết hơn. Tuy nhiên nếu bạn đã làm hỗn hợp bị lỏng quá thì nên nhúng bánh sampa thật nhanh tay để cho bánh vẫn còn khô bên trong, lúc đó bánh ngấm bớt nước từ hỗn hợp mascarpone là vừa.</li>
        <li>Không nên cho gelatine vào bánh sẽ phá hỏng đi chất liệu của bánh. Ý kiến của mình là vậy. Một số cửa hàng bánh bình dân mình ăn thử, họ có cho gelatine vào bánh để bánh đứng được tốt hơn và dễ cắt thành miếng để đóng gói hơn, tuy nhiên ăn rất tệ. Trong khi những nhà hàng Ý mình ăn thì thà họ bánh mềm xiên xẹo còn hơn là cho gelatine.</li>
        <li>Nếu làm theo cách tiramisù truyền thống thì bỏ qua khâu 4 và 5, cũng không dùng rượu nhé.</li>
        <li>Bánh Tiramisù Ý vốn dĩ rất mềm nên khâu múc bánh ra đôi lúc khó khăn vì nó dễ xiên xẹo lắm. Một số nơi mình ăn họ hay cho bánh vào từng cốc riêng rồi dùng thìa xúc. Nếu bạn nào muốn làm trong cốc thì nhúng bánh Sampa xong nhớ bẻ vụn nhỏ ra rồi xếp vào ly là được 🙂
        <p><figure data-shortcode="caption" id="attachment_2017" aria-describedby="caption-attachment-2017" style="width: 2880px" class="wp-caption alignnone"><img data-attachment-id="2017" data-permalink="https://mykitchies.com/2018-05-05-12-13-011457772481/" data-orig-file="https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-011457772481.jpg" data-orig-size="2880,2160" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="2018-05-05-12-13-011457772481.jpg" data-image-description="" data-medium-file="https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-011457772481.jpg?w=300" data-large-file="https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-011457772481.jpg?w=736" class="alignnone size-full wp-image-2017" src="https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-011457772481.jpg?w=736" alt="2018-05-05-12-13-011457772481.jpg" srcset="https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-011457772481.jpg?w=736 736w, https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-011457772481.jpg?w=1472 1472w, https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-011457772481.jpg?w=150 150w, https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-011457772481.jpg?w=300 300w, https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-011457772481.jpg?w=768 768w, https://mykitchies.files.wordpress.com/2018/05/2018-05-05-12-13-011457772481.jpg?w=1024 1024w" sizes="(max-width: 736px) 100vw, 736px"   /><figcaption id="caption-attachment-2017" class="wp-caption-text">mình lấy ẩu nên bánh có phần xiên xẹo 😛 cơ mà rất đắt hàng</figcaption></figure></li>
        </ol>
        <p>Chúc các bạn thành công với món Tiramisù Ý nhé 🙂 Để theo dõi bài viết mới các bạn có thể ghé thăm Facebook Mykitchies &#8211; Bếp Á Âu của mình</p>`,
    },
    {
        namefood = 'Salad Nga với Táo ',
        tye: 'Món Âu',
        img: 'Mind-X\Kitchies\img\3.1.jpg',
        content: ``,
    },
    {
        namefood = 'Cheesecake xoài không cần lò nướng ',
        tye: 'Món Âu',
        img: 'Mind-X\Kitchies\img\4.1.jpg',
        content: ``,
    },
];